import Header from "../components/header/Header";
import React from "react";
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout =({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Infant:wght@300;400;500;600;700&family=Mulish:wght@200;300;400;500;600&display=swap"
          rel="stylesheet"
        />
        <title></title>
      </head>
      <body>
      <Header/>
      {children}
      </body>
    </html>
  )
}

export default RootLayout;
